theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
facebook_username: mattparrett 
github_username: mparrett
twitter_username: mattparrett
insta_username: mparrettaz
linkedin_username: mattparrett
